# POST http://localhost:3000/users
# Content-Type : application/json

# {
#     "name" : "priya",
#     "id" : 2
# }



POST http://localhost:3000/postss
Content-Type : application/json

{
    "name" : "priyaa",
    "id" : 2
}