###

GET http://localhost:3000/api/data

###

GET http://localhost:3000/

###
POST http://localhost:3000/api/data
Content-Type: application/json

{
    "name": "priya"
}


###

DELETE http://localhost:3000/api/data